# Blueboard 2.0 compose stuff
# YAAAY
version: '3.9'

services:
  blueboard:
    build:
      context: ./app
    hostname: blueboard
    container_name: blueboard
    image: blueboard
    networks:
      blueboard:
        ipv4_address: 172.128.3.1
    volumes:
      - ../:/var/www/api/
      - ./data/logs:/var/log/
      - ./data/root:/root
    depends_on:
      - mysql
      - redis
    restart: on-failure

  blueboard-shell:
    image: blueboard
    command: bash
    profiles:
      - nope
    volumes:
      - ../:/var/www/api/
      - ./data/logs:/var/log/
      - ./data/root:/root
    hostname: blueboard-shell
    container_name: blueboard-shell
    networks:
      blueboard:
        # Yep, I'm really that mature.
        ipv4_address: 172.128.3.69

  cron:
    build: ./cron
    hostname: blueboard-cron
    container_name: blueboard-cron
    networks:
      blueboard:
        ipv4_address: 172.128.3.2
    volumes:
      - ../:/var/www/api/
      - ./data/logs:/var/log/
      - ./data/root:/root
    depends_on:
      - blueboard
      - mysql
      - redis
    restart: on-failure

  horizon:
    build: ./horizon
    hostname: blueboard-horizon
    container_name: blueboard-horizon
    networks:
      blueboard:
        ipv4_address: 172.128.3.3
    volumes:
      - ../:/var/www/api/
      - ./data/logs:/var/log/
      - ./data/root:/root
    depends_on:
      - app
      - mysql
      - redis
    restart: on-failure

  router:
    image: qoomon/docker-host
    container_name: blueboard-router
    hostname: blueboard-router
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    environment:
      - PORTS=3306,9000
    networks:
      blueboard:
        ipv4_address: 172.128.3.7

  mysql:
    image: mariadb:10.6.5
    container_name: blueboard-mysql
    hostname: blueboard-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=2021!llgapp
      - MYSQL_DATABASE=lovassyapp
      - MYSQL_USER=lovassyapp
      - MYSQL_PASSWORD=lOvAsSyApP!2021
      - MYSQL_ROOT_HOST=%
    restart: on-failure
    networks:
      blueboard:
        ipv4_address: 172.128.3.4
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:3307:3306

  redis:
    image: redis:alpine
    container_name: blueboard-redis
    hostname: blueboard-redis
    networks:
      blueboard:
        ipv4_address: 172.128.3.5
    ports:
      - 127.0.0.1:6379:6379
    command: redis-server /redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ./data/redis:/data
      - ./redis:/redis

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    container_name: blueboard-soketi
    hostname: blueboard-soketi
    environment:
      SOKETI_DEBUG: '0'
      SOKETI_METRICS_SERVER_PORT: '9601'
      SOKETI_DB_MYSQL_HOST: '172.128.3.4'
      SOKETI_DB_MYSQL_PORT: '3306'
      SOKETI_DB_MYSQL_USERNAME: 'lovassyapp'
      SOKETI_DB_MYSQL_PASSWORD: 'lOvAsSyApP!2021'
      SOKETI_DB_MYSQL_DATABASE: 'lovassyapp'
      SOKETI_APP_MANAGER_DRIVER: 'mysql'
      SOKETI_APP_MANAGER_MYSQL_TABLE: 'soketi_apps'
      SOKETI_APP_MANAGER_MYSQL_VERSION: '10'
      SOKETI_APP_MANAGER_MYSQL_USE_V2: 'false'
    depends_on:
      - mysql
    ports:
      - 6001:6001
      - 127.0.0.1:9601:9601
    networks:
      blueboard:
        ipv4_address: 172.128.3.6

networks:
  blueboard:
    driver: bridge
    ipam:
      config:
        - subnet: 172.128.3.0/16
