version: '3.9'

services:
  blueboard:
    extends:
      file: ../apps/blueboard/docker/docker-compose.yml
      service: blueboard

  blueboard-shell:
    extends:
      file: ../apps/blueboard/docker/docker-compose.yml
      service: blueboard-shell

  cron:
    extends:
      file: ../apps/blueboard/docker/docker-compose.yml
      service: cron

  horizon:
    extends:
      file: ../apps/blueboard/docker/docker-compose.yml
      service: horizon

  router:
    extends:
      file: ../apps/blueboard/docker/docker-compose.yml
      service: router

  mysql:
    extends:
      file: ../apps/blueboard/docker/docker-compose.yml
      service: mysql

  redis:
    extends:
      file: ../apps/blueboard/docker/docker-compose.yml
      service: redis

  soketi:
    extends:
      file: ../apps/blueboard/docker/docker-compose.yml
      service: soketi

  nginx:
    image: nginx:alpine
    container_name: llgapp-nginx
    hostname: llgapp-nginx
    networks:
      blueboard:
        ipv4_address: 172.128.3.8
    volumes:
      - ../apps/blueboard/:/var/www/api/
      - ../apps/boardlight:/var/www/frontend/
      - ./nginx/:/etc/nginx/conf.d/
      - ./data/logs:/var/log/
      - ./data/root:/root
    ports:
      - 80:80
      - 443:443
    depends_on:
      - blueboard

networks:
  blueboard:
    driver: bridge
    ipam:
      config:
        - subnet: 172.128.3.0/16
